### ISSUE TITLE
[Bug] Special characters not authorised in the log in but authorised in the register

### ISSUE THREAD

**Issue by Angel-Karasu** [Crossoufire/MyLists#17]
We can register an account with special characters in the password but can't log in with special characters in the password

**Comment by Crossoufire** [comment]
Hello,

Thank you for reporting this bug. Could you please provide a more detailed example? 

- The special characters you used in the password.
- Any error messages you received.
- (Optional) The steps you followed when encountering the issue.

I tested using special characters in the password, and it worked on my end, so any additional details you can give me would help me tackle this problem.

Thank you!

**Comment by Angel-Karasu** [comment]
The special character I want to use is `€`, I can register with this character in my password or I can change my password and set it, but when I want to connect, when I click on the login button, nothing happens.

**Comment by Crossoufire** [comment]
Thank you for the information. Normally the problem is now resolved.
