### ISSUE TITLE
View user profile page without the need to log in

### ISSUE THREAD

**Issue by ZeroSoundsCool** [Crossoufire/MyLists#2]
I wanna share my profile page and my lists to the public

**Comment by SPRATAY** [comment]
good idea, why problem?

**Comment by ZeroSoundsCool** [comment]
How can I do that?

**Comment by ZeroSoundsCool** [comment]
when I share my profile link to someone else, it requires them to sign up, can you change that?

**Comment by SPRATAY** [comment]
> when I share my profile link to someone else, it requires them to sign up, can you change that?

@Crossoufire ?

**Comment by Crossoufire** [comment]
I can try to implement that, would you like only the profile page or also the lists ?

**Comment by SPRATAY** [comment]
> I can try to implement that, would you like only the profile page or also the lists ?

go profile page, other we'll see in the future

**Comment by ZeroSoundsCool** [comment]
> I can try to implement that, would you like only the profile page or also the lists ?

both, when someone asks me what anime have you watched or movies ,.. I can just link them my profile link
plus would be great if they can see each rating/comment I've made (cuz imdb don't show ratings)

**Comment by SPRATAY** [comment]
> > I can try to implement that, would you like only the profile page or also the lists ?
> 
> both, when someone asks me what anime have you watched or movies ,.. I can just link them my profile link plus would be great if they can see each rating/comment I've made (cuz imdb don't show ratings)

It would be nice to make registration optional, those who want to hide their profile add the option in the settings

**Comment by Crossoufire** [comment]
I'm currently working on creating privacy settings with three levels: **private**, **restricted**, and **public**. 
- The **restricted** setting (the default), allows only connected users to view the profile and lists. 
- The **public** setting makes everything visible to everyone. 
- The **private** setting, which I'll implement later, will restrict access to accepted followers only
